### ISSUE TITLE
error: attribute '/mnt/nix/store/<id>/rust-toolchain.toml' missing at /mnt/nix/store/<id>/pkgs-set.nix:50:12

### ISSUE THREAD

**Issue by I-Want-ToBelieve** [yusdacra/nix-cargo-integration#107]
Does anyone here know how to solve this problem?
https://github.com/rxyhn/dotfiles/issues/7#issue-1507003219

**Comment by yusdacra** [comment]
This issue was already solved. The repository in question needs to update helix, or you yourself should.
