### ISSUE TITLE
Can't get template to work ... easily.

### ISSUE THREAD

**Issue by waalge** [yusdacra/nix-cargo-integration#111]
```
nix-shell -p cargo
cargo new hello-x
nix flake init -t github:yusdacra/nix-cargo-integration
git add .
nix develop
```
To which it replies 
```
warning: No packages found. Did you add the `package.metadata.nix` section to a `Cargo.toml` and added `build = true` under it?
error:
       … while calling the 'mapAttrs' builtin 
       ...
```
Helpful, so then 
```
echo "[package.metadata.nix]" >> Cargo.toml
echo "build = true" >> Cargo.toml
nix develop
```
replies 
```
...
      error: attribute 'devShells' missing

       at /nix/store/ph69dv42xyf10i4lcbxn53xkkji98456-source/src/build/default.nix:217:11:

          216|   unwrappedPackage = _outputs.packages.${pkgs.system}.${cargoPkg.name};
          217|   shell = _outputs.devShells.${pkgs.system}.${cargoPkg.name};
             |           ^
          218| in rec {
```
Following [this discussion](https://github.com/yusdacra/nix-cargo-integration/discussions/109), I mod the flake to 
```
cat flake.nix
{
  inputs.nci.url = "github:yusdacra/nix-cargo-integration";

  outputs = inputs:
    inputs.nci.lib.makeOutputs {
      config = common: {
        outputs.defaults = {
          package = "hello-x";
        };
      };
      root = ./.;
    };
}
```
But the result of `nix develop` is unchanged 
Running `cargo run` (to generate `Cargo.lock`) 
```
cargo run 
git add Cargo.lock
```
Then 
```
nix develop
```
Ok - this works! 

I think the error messages and docs could be clearer on this.
Is it possible to get a template such that I don't have to first `nix-shell -p cargo` _etc_.  

Happy to assist if you agree there's something to be done here.

Thanks,

**Comment by yusdacra** [comment]
Thanks for the info. Can you try out #110 ? It should handle what you are talking about.

**Comment by waalge** [comment]
A bit smoother. Still had some issues and it took several attempts to get there.

```
nix-shell -p cargo
cargo new hello-x
cd hello-x/
nix flake init -t github:yusdacra/nix-cargo-integration/919017ea66b17f20df6c5721aacdbcb5e35924f1
hx flake.nix # Edit url to point at commit; rename example crate.
cargo run
git add .
nix run .#generate-lockfiles # Suggested in other error messages, but also fails
nix develop # Fails
nix develop .#hello-x
```
Most of these issues can easily avoided with some docs - I was just guessing.

How stupid is it to have an devShell just to init a new project  so that `cargo` can be made available via the flake, 
and there is a command to generate the lock file and add it to git without manual work?
eg it can be dropped into without a crate being available.

```
mkdir hello-x
cd hello-x 
nix flake init -t github:yusdacra/nix-cargo-integration
# Either `nix run .#init` Or 
nix develop .#bare
cargo init ... 
nci-update-crate # command exposed in devshell. Ensures that crate correctly added to flake & set as default. 
```

Maybe this is silly.

**Comment by yusdacra** [comment]
The generate-lockfiles app *should* be working, can you post the error message? Or make a repo with the erroring flake and etc. Thanks!

**Comment by waalge** [comment]
The annoying faff is having to drop into a nix-shell to use cargo to init.
Maybe the template includes the files output "cargo init" so that it can be entered immediately?

I'll make a repo...

**Comment by waalge** [comment]
Is it that there is a path that is absolute rather than relative?
```
[nix-shell:~/tmp/hello-x]$ nix run .#generate-lockfiles
trace: Cargo.lock not found for project at path .
Please ensure the lockfile exists for your project.
If you are using a VCS, ensure the lockfile is added to the VCS and not ignored (eg. run `git add /Cargo.lock` for git).

This project will be skipped and won't have any outputs generated.
Run `nix run .#generate-lockfiles` to generate lockfiles for projects that don't have one.

error: manifest path `/Cargo.toml` does not exist
fatal: /Cargo.lock: '/Cargo.lock' is outside repository at '/home/waalge/tmp/hello-x'
```

**Comment by waalge** [comment]
https://github.com/waalge/hello-x-nci/commits/main

Some notes of input/output in the commit messages.

**Comment by yusdacra** [comment]
> Maybe the template includes the files output "cargo init" so that it can be entered immediately?

There is a `simple-crate` template included in the templates (you can use it with `nix flake init -t github:yusdacra/nix-cargo-integration/flake-parts#simple-crate`). That is what you mean by that I assume?

> Is it that there is a path that is absolute rather than relative?

This is a bug, I fixed it just now. Please try it again.

**Comment by waalge** [comment]
That is exactly what I mean :) it works much more smoothly. 

If I knew this existed, I would have used this multiple times in the past month to quick spin up a repo to try some library. 

Its a bit of a stall for there to be no default shell, and no help message 
```
$ nix develop # <-- BAD
warning: Git tree '/home/waalge/tmp/hello-nci' is dirty
error: flake 'git+file:///home/waalge/tmp/hello-nci' does not provide attribute 'devShells.x86_64-linux.default', 'devShell.x86_64-linux', 'packages.x86_64-linux.default' or 'defaultPackage.x86_64-linux'
       Did you mean devShells?
 $ nix develop .#my-crate # <-- GOOD
```


Don't want to over engineer this. But. 
Every user is going to want to immediately rename "my-crate". Which has to be done in multiple places. There's an option to add a `welcomeText` onto a template, and/or pass args
https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake-init.html#options
I've not used this, but i'd be interested in trying

**Comment by waalge** [comment]
I don't think templates with args exist.

I've made some changes here:

https://github.com/waalge/nix-cargo-integration/tree/waalge/flake-parts

**Comment by yusdacra** [comment]
Ok, I added `welcomeText`'s to the examples and tweaked them a bit more. Would be happy if you could check them out, hopefully it should address the issues you had.

**Comment by waalge** [comment]
Think it looks good. 

There are other fairly immediate pit falls 
- rust analyzer not working, and having to add 
https://discourse.nixos.org/t/rust-src-not-found-and-other-misadventures-of-developing-rust-on-nixos/11570/15
I would have thought this was pretty generic. 
- git submodules not being supported, but this is an artifact of flakes&git so ... i don't think there's anything to do here. 
Its just painful how unhelpful nix error messages are.

**Comment by yusdacra** [comment]
> rust analyzer not working, and having to add

Is this not working in the nix-cargo-integration devshell?

**Comment by waalge** [comment]
hmm. Maybe it was and then I broke it... not sure. Maybe await someone else reporting it as an issue. 

Thanks for assisting with this, and this project
