### ISSUE TITLE
Local dependency examples 

### ISSUE THREAD

**Issue by waalge** [yusdacra/nix-cargo-integration#113]
Are there any examples showing how to have a local dependency not in the scope of the git? 

I've tried using `path = ...` with an absolute path, but it says 
```
error: could not find crate  '<crate_name>'
``` 
If I've already dropped into a devshell, it doesn't seem to break immediately, but if I leave and come back (I haven't isolated this very well) it's unable to re-enter

**Comment by yusdacra** [comment]
I'm not exactly sure I understand what you are doing here, can you provide an MRE?

**Comment by waalge** [comment]
https://github.com/waalge/hello-nci

This is not a MRE of my problem, yet. I hit a bug from the initial setup - rel path wasn't liked.

**Comment by yusdacra** [comment]
> [waalge/hello-nci](https://github.com/waalge/hello-nci)
> 
> This is not a MRE of my problem, yet. I hit a bug from the initial setup - rel path wasn't liked.

I fixed the relpath problem. About your original issue, flakes do not support paths not added to Git.

**Comment by waalge** [comment]
i'll try again. 

flakes support urls to the interwebs. Can I not also allow it to reach for a path needed for a dependency instead?

**Comment by yusdacra** [comment]
> Can I not also allow it to reach for a path needed for a dependency instead?

I'm not exactly sure what you mean by this? I would prefer if you showed what is wrong in that repository you linked.

**Comment by waalge** [comment]
I've not circled back to this - sorry - I'll close this.

I think my Q is possibly more about how flakes work in general.
