### ISSUE TITLE
Importing a `devshell.toml` fails when running `nix develop`

### ISSUE THREAD

**Issue by Austreelis** [yusdacra/nix-cargo-integration#12]
I have a basic flake:
```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    nixCargoIntegration = {
      url = "github:yusdacra/nix-cargo-integration";
      #url = "gitlab:Austreelis/nix-cargo-integration";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
  outputs = inputs: inputs.nixCargoIntegration.lib.makeOutputs {
    root = ./.;
    buildPlatform = "crate2nix";
    defaultOutputs = {
      package = "utf8-bufread";
    };
  };
}
```

And a basic `devshell.toml` in my repo's root directory:

```toml
[[commands]]
package = "hello"
```

running `nix develop` fails with the following error:
```
> nix develop
error: value is a function while a set was expected

       at /nix/store/ig5xhkhfhdsa249bs65j7g42h45hm8s4-source/devShell.nix:116:17:

          115|           then { config = combineWithBase devshellConfig; imports = [ ]; }
          116|           else {
             |                 ^
          117|             config = combineWithBase importedDevshell.config;
(use '--show-trace' to show detailed location information)
```

After some digging, it turns out the value returned by [devshell's `importTOML`](https://github.com/numtide/devshell/blob/master/nix/importTOML.nix) is a function (that is: `importedDevshell` is a function, one taking `lib` as argument).

When applying the following patch:

```diff
diff --git a/devShell.nix b/devShell.nix
index 86c78e9..550c100 100644
--- a/devShell.nix
+++ b/devShell.nix
@@ -13,7 +13,9 @@ let
   devshellFilePath = common.prevRoot + "/devshell.toml";
 
   # Import the devshell specified in devshell.toml if it exists
-  importedDevshell = if (builtins.pathExists devshellFilePath) then (pkgs.devshell.importTOML devshellFilePath) else null;
+  importedDevshell = if (builtins.pathExists devshellFilePath)
+    then (pkgs.devshell.importTOML devshellFilePath { inherit lib; })
+    else null;
 
   # Create a base devshell config
   baseConfig = {
```

The shell launches successfully.

I don't know if this is intended or not, but if it's an actual issue, I have a PR ready [here](https://gitlab.com/Austreelis/nix-cargo-integration) :slightly_smiling_face: 
I quickly looked into the tests but I don't think there is one for projects with a `devshell.toml` ? That's also something I could add if that's welcome.

**Comment by yusdacra** [comment]
Ah interesting, looks like it got changed. And yeah it doesn't have a test case so the CI or I couldn't catch it. The fix and the test case would be welcome as a PR :+1:
