### ISSUE TITLE
Cross compiling losing std. I think

### ISSUE THREAD

**Issue by waalge** [yusdacra/nix-cargo-integration#127]
hello again. 

I tried to wrap a rust wasm project up with nci. 
I got an error I cannot resolve.
```sample
  --> /home/waalge/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_hot_reload-0.3.1/src/diff.rs:6:20
   |
6  | struct OldChildren(IndexMap<LNode, Vec<usize>>);
   |                    ^^^^^^^^ -----  ---------- supplied 2 generic arguments
   |                    |
   |                    expected 3 generic arguments
   |
note: struct defined here, with 3 generic parameters: `K`, `V`, `S`
  --> /home/waalge/.cargo/registry/src/index.crates.io-6f17d22bba15001f/indexmap-1.9.3/src/map.rs:76:12
   |
76 | pub struct IndexMap<K, V, S> {
   |            ^^^^^^^^ -  -  -
help: add missing generic argument
   |
6  | struct OldChildren(IndexMap<LNode, Vec<usize>, S>);
   |                                              +++

For more information about this error, try `rustc --explain E0107`.
error: could not compile `leptos_hot_reload` (lib) due to previous error
```
After much staring at things I don't really understand I'm guessing that cargo isn't providing `std` 
So i'm getting the "wrong" index map.
https://github.com/bluss/indexmap/blob/861fad73de14b7f08d2dc56ed83607aef621b42e/src/map.rs#L70

Any thoughts on this? 
I know https://github.com/yusdacra/nix-cargo-integration/issues/5 is still open. 

##### Reproduce

https://github.com/waalge/aiken-play

**Comment by yusdacra** [comment]
Did you take a look at https://github.com/yusdacra/nix-cargo-integration/tree/master/examples/cross-compile-wasm ?

**Comment by waalge** [comment]
:pray: That i hadnt seen. 
Its flake input nci url  is a local btw. 

But yes, this absoutely solves it. 
Thanks! And for unreasonably fast response :)

**Comment by waalge** [comment]
solved
