### ISSUE TITLE
After updating to the latest version, "attribute 'relPath' missing" when generating lockfile

### ISSUE THREAD

**Issue by riskygit** [yusdacra/nix-cargo-integration#132]
Hi, I think there may be a bug with the latest version. I changed relPath to path (`./.`) and updated all the other items in the changelog, but I can't generate a lockfile. It says relPath is missing.

**Comment by yusdacra** [comment]
Thanks for reporting! I pushed a fix to master, it should fix this issue, can you please try updating and trying again?

**Comment by riskygit** [comment]
Yes, it's fixed. Thank you!
