### ISSUE TITLE
Exposing tests to flake

### ISSUE THREAD

**Issue by szg251** [yusdacra/nix-cargo-integration#136]
I want to run tests separately from the build step, using my flake's `checks`, but I couldn't find a way to expose the test executable from nci.
My crate.nix:
```nix
{ ... }: {
  perSystem =
    { config
    , shellHook
    , ...
    }:
    let
      crateName = "my-crate";
    in
    {
      nci.projects.${crateName}.path = ./.;
      nci.crates.${crateName} = { };
    };
}
```

Relevant part of my flake.nix:
```nix 
  perSystem = { system, config, ... }:
    devShells.default = config.nci.outputs.${crateName}.devShell;
    packages.default = config.nci.outputs.${crateName}.packages.release;
    checks.default = config.nci.outputs.${crateName}.checks; # <-- Something like this would be nice
}
```

**Comment by yusdacra** [comment]
I pushed a new feature that should do what you said here. There is now a `check` output that only runs `cargo test`, and uses the package generated for the profile specified in a `nci.crates.<name>.checkProfile` option (by default this is the release profile) as it's base.

**Comment by szg251** [comment]
Awesome, thanks!
