### ISSUE TITLE
`drvConfig.mkDerivation.meta` is not propagated to the derivation

### ISSUE THREAD

**Issue by liff** [yusdacra/nix-cargo-integration#137]
From the [example](https://github.com/yusdacra/nix-cargo-integration/blob/066b20df90fcccc9781d6458e553a17e2521b60e/src/options/drvConfig.nix#L13-L25) I understood that the attributes in `mkDerivation` would be included in the derivation pretty much verbatim. However, only the `license` attribute is present.

[Here is a repository demonstrating the problem](https://github.com/liff/nix-cargo-integration-issue-137), and a command:

```shell
$ nix eval github:liff/nix-cargo-integration-issue-137#default.meta.mainProgram
error: flake 'github:liff/nix-cargo-integration-issue-137' does not provide attribute 'packages.x86_64-linux.default.meta.mainProgram', 'legacyPackages.x86_64-linux.default.meta.mainProgram' or 'default.meta.mainProgram'
```

The `meta` attributes is defined in [crates.nix](https://github.com/liff/nix-cargo-integration-issue-137/blob/main/crates.nix#L15).
Whether it’s in `nci.projects` or `nci.crates` makes no difference.

**Comment by yusdacra** [comment]
This should be fixed after https://github.com/nix-community/dream2nix/pull/716 is merged and nci updates to include the latest d2n commit
