### ISSUE TITLE
The overriding stdenv example doesn't seem to work

### ISSUE THREAD

**Issue by riskygit** [yusdacra/nix-cargo-integration#142]
I've followed the simple example, but I'm seeing:

```
       error: The option `mkDerivation.stdenv' does not exist. Definition values:
       - In `<unknown-file>': <derivation stdenv-linux>
```

Edit: I downloaded the examples and the same issue is occurring.

**Comment by riskygit** [comment]
Haven't been able to achieve a workaround... I know Helix switched to using crane and seems to have this working, but I do prefer this project due to simplicity.

**Comment by yusdacra** [comment]
This looks like it was because dream2nix changed something upstream, and the CI wasn't running tests for that specific example. `deps.stdenv` should be used instead of `mkDerivation.stdenv`. I've updated the examples to match that.
