### ISSUE TITLE
`attribute checkProfile missing`

### ISSUE THREAD

**Issue by quinn-dougherty** [yusdacra/nix-cargo-integration#147]
When I attempt `nix flake show`: 

```

         at /nix/store/h0rvqbjdbjjfw8whjyfjn1ny8kidd3j3-source/src/implementation.nix:169:23:

          168|               };
          169|               check = import ./functions/mkCheckOnlyPackage.nix packages.${crate.checkProfile};
             |                       ^
          170|             }

       … while calling anonymous lambda

         at /nix/store/h0rvqbjdbjjfw8whjyfjn1ny8kidd3j3-source/src/functions/mkCheckOnlyPackage.nix:1:1:

            1| pkg: let
             | ^
            2|   cfg = {lib, ...}: {

       error: attribute 'checkProfile' missing

       at /nix/store/h0rvqbjdbjjfw8whjyfjn1ny8kidd3j3-source/src/implementation.nix:169:76:

          168|               };
          169|               check = import ./functions/mkCheckOnlyPackage.nix packages.${crate.checkProfile};
             |                                                                            ^
          170|             }
```

full trace: https://pastebin.com/D6xqERsR

I tried overriding the default that is claimed in the documentation and code with `crate.<name>.checkProfile = "release";`, but it didn't help.

I read this issue https://github.com/yusdacra/nix-cargo-integration/issues/145 but it doesn't seem to have an answer to this. 

Here's the `crates.nix`: https://github.com/cspr-rad/ltl-actus/blob/master/nix/crates/default.nix 

the individual crate files are just dummies currently, but that doesn't usually interfere. In this repo: 

- `nix build .#checks.x86_64-linux.ltl` (a lib crate) works
- `nix build .#checks.x86_64-linux.actus` (a lib crate) works
- `nix build .#checks.x86_64-linux.cli` (a bin crate) breaks with the above error.

**Comment by yusdacra** [comment]
Pushed a new commit, lemme know if it helps

**Comment by quinn-dougherty** [comment]
just `nix flake update` and the behavior is the same.

**Comment by quinn-dougherty** [comment]
`nix flake show` runs now
