### ISSUE TITLE
Using `depsDrvConfig` with `nix shell`

### ISSUE THREAD

**Issue by nejucomo** [yusdacra/nix-cargo-integration#149]
Hi,

I'm unable to get "nix shell" to work with a basic single crate repo with the `git2` dependency (which transitively depends on `openssl-sys` crate, thus the openssl library).

As a newcomer to nix, it took me a while of google about nix openssl problems plus reading the nci source to find `depsDrvConfig` and I came up with this recipe that can successfully build:

```
{
  description = "nix-graphviz lib crate and binary";

  inputs.nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
  inputs.nci.url = "github:yusdacra/nix-cargo-integration";
  inputs.nci.inputs.nixpkgs.follows = "nixpkgs";
  inputs.parts.url = "github:hercules-ci/flake-parts";
  inputs.parts.inputs.nixpkgs-lib.follows = "nixpkgs";

  outputs = inputs @ { self, nixpkgs, nci, parts }:
  let
    pkg-name = "git-graphviz";
  in parts.lib.mkFlake { inherit inputs; } {
    systems = ["x86_64-linux"];
    imports = [
      nci.flakeModule
      ./crates.nix
    ];
    perSystem = { pkgs, config, ... }:
    let
      crateOutputs = config.nci.outputs.${pkg-name};
      openssl-tweak = {
        # https://discourse.nixos.org/t/rust-pkg-config-issue-on-openssl-dependency/12354/6
        mkDerivation = {
          nativeBuildInputs = [
            pkgs.pkg-config
          ];
          buildInputs = [
            pkgs.openssl
          ];
        };
      };
    in {
      nci.crates.${pkg-name} = {
        depsDrvConfig = openssl-tweak;
        drvConfig = openssl-tweak;
      };

      packages.default = crateOutputs.packages.release;
      devShells.default = crateOutputs.devShell;
    };
  };
}
```

This successfully builds via `nix build` (but it doesn't seem to cache dependencies and rebuilds them every time).

However, if I run `nix shell`, it fails unable to find `openssl` via `pkg-config`.

How can I properly define a `nix shell`? Also, how can I cache dependency builds?

**Comment by riskygit** [comment]
Put `crateOutputs.devShell` into the `inputFrom` list of a new shell (via `pkgs.mkShell` or another method) and add the required build inputs.

**Comment by yusdacra** [comment]
Can you point me to the repo where this is reproducible? Or give me an MRE?

**Comment by yusdacra** [comment]
sorry, i can't repro this so i'll close the issue, please open it if you can provide a repro
