### ISSUE TITLE
Using numtide/devshell for the derived devshell

### ISSUE THREAD

**Issue by oddlama** [yusdacra/nix-cargo-integration#158]
As far as I can tell, the only supported way to get a customized devshell is to override the devshell that is provided via `config.nci.outputs.${projectName}.devShell`. I frequently find myself adding pre-commit-hooks, extra packages or environment variables:

```nix
devShells.default = config.nci.outputs.${projectName}.devShell.overrideAttrs (old: {
  nativeBuildInputs = (old.nativeBuildInputs or []) ++ [pkgs.cargo-release];

  shellHook = ''
    export LD_LIBRARY_PATH="...:$LD_LIBRARY_PATH"
    ${old.shellHook or ""}
    ${config.pre-commit.installationScript}
  '';
});
```

This is a bit unergonomic, especially if you have to redo this on a lot of projects. There is a wrapper called [numtide/devshell](https://github.com/numtide/devshell) (you might know it), that also has flake-parts support and allows me to add packages and environment variables via proper options in flake-parts:

```nix
devshells.default = {
  packages = [pkgs.cargo-release];
  devshell.startup.pre-commit.text = config.pre-commit.installationScript;
  env = [ { name = "LD_LIBRARY_PATH"; prefix = "..."; } ];
};
```

I find this a lot more maintainable, but I love nix-cargo-integration and cannot live without it anymore. Unfortunately I cannot figure out a good way to get a numtide devshell out of it without adding a lot of stuff to each project.

Is there a simple way to convert the devshell to a numtide based devshell? And if there isn't, would you be open to adding direct support for exporting a numtide/devshell to this project? I think this could be quite ergonomic, since both projects already support flake-parts.

**Comment by yusdacra** [comment]
This would be possible, nix-cargo-integration used to use numtide devshell but I stopped using it since I didn't think it was necessary as users could just set that devshell up themselves, and add the inputs from the devshell NCI generates there, so that part is already possible.

It might be a good idea to include a `passthru.numtideEnv` attribute (and just `env` for everything else) in the generated shell to pull the environment variables into user-created numtide devshell easier. And then just add all the inputs via the generated shell's `packages` attribute. This should solve what you are describing I think? You would just be able to do:

```nix
devshells.default = let
  nciShell = config.nci.outputs."crate".devShell;
in {
  packages = nciShell.packages ++ [pkgs.cargo-release];
  devshell.startup.pre-commit.text = config.pre-commit.installationScript;
  env =nciShell.numtideEnv ++ [ { name = "LD_LIBRARY_PATH"; prefix = "..."; } ];
};
```

Maybe also just add a contrib dir or something similar to put a `initializeNumtideDevshellFromNciShells.nix` (awfully long name i know) module for flake-parts that does it automatically once you include that module?

**Comment by oddlama** [comment]
That would definitely be a great start! Since both project are using flake-parts I was thinking about having a setting that would have nci define the devshell directly - so essentially converting the stuff from your comment into a opt-in option:

```nix
nci.projects.example.path = ./.;
nci.projects.example.addToDevshells = ["default"];

devShells.default.packages = [pkgs.cargo-release];
# ...
```

What do you think?

**Comment by yusdacra** [comment]
I'm not sure if a config option is necessary, I think a simple module import would do the job. Just importing something like a `flakeModules.numtideImportGeneratedShells` that will automatically import everything from the generated shells into numtide devshells with the same name should work well, and you can just pick and choose whichever ones you want to actually use, if it exported them under something like a `nci.outputs.<name>.numtideDevShell`.

**Comment by yusdacra** [comment]
I made it so that every devshell will have `env` and `packages` exposed so it should be possible to write a module that does this now. So you should just be able to extend `nci.outputs.<name>` to have a `numtideDevShell` option or something and just use `nci.outputs.<name>.devShell.<env/packages>` to get either the environment variables or the inputs,

**Comment by oddlama** [comment]
Sounds great, thanks a lot. I'll report back when I have made a module using the new options

**Comment by oddlama** [comment]
I just tried the following, but unfortunately cargo (and all other tools) are missing from the resulting devshell. At first I thought about using `packagesFrom` but the same thing seems to occur. Is there another output that contains all the tooling that I am missing right now?

```nix
    devshells.default = {
      packages = config.nci.outputs."example".devShell.packages;
      env = lib.mapAttrsToList (k: v: { name = k; value = v; }) config.nci.outputs."example".devShell.env;
    };
```

**Comment by yusdacra** [comment]
Oh yeah I think I forgot to mention that the toolchain itself isn't added to those. If you add the toolchain from `config.nci.toolchains.shell` should work?

**Comment by oddlama** [comment]
Ah nice, it seems to work on one of my simple repositories by doing this:

```nix
    devshells.default = {
      packagesFrom = [config.nci.toolchains.shell];
      packages = config.nci.outputs."example".devShell.packages ++ [config.nci.toolchains.shell];
      env = lib.mapAttrsToList (k: v: { name = k; value = v; }) config.nci.outputs."example".devShell.env;
    };
```

Just adding it to `packages` will miss the cc and linker, and just adding it to `packagesFrom` misses cargo. So apparently you need it in both, but I'm not certain at this point if that just working by accident or whether this is intended by the way numtide/devshell is designed.

**Comment by oddlama** [comment]
I've arrived at the module below now, in case anyone is interested. I think I cannot be extended to have proper multi-crate support, because it is unclear how to merge env variables from different crates properly. Some would need to be made unique and added together (LD_LIBRARY_PATH), some could conflict (architecture stuff). So currently all env variables are added to the shell.


`devshell-from-nci.nix`:

```nix
{
  perSystem = {
    lib,
    config,
    ...
  }: {
    options.nci.crates = lib.mkOption {
      type = lib.types.lazyAttrsOf (lib.types.submoduleWith {
        modules = [
          {
            options = {
              numtideDevshell = lib.mkOption {
                type = lib.types.nullOr lib.types.str;
                default = null;
                description = ''
                  If set, the given numtide devshell will be populated with
                  the required packages and environment variables for this crate.
                '';
              };
            };
          }
        ];
      });
    };

    config.devshells = lib.mkMerge (lib.flatten (lib.flip lib.mapAttrsToList config.nci.crates (project: cfg:
      lib.optional (cfg.numtideDevshell != null) {
        ${cfg.numtideDevshell} = {
          packagesFrom = [config.nci.toolchains.shell];
          packages = config.nci.outputs.${project}.devShell.packages ++ [config.nci.toolchains.shell];
          env =
            lib.mapAttrsToList (k: v: {
              name = k;
              value = v;
            })
            config.nci.outputs.${project}.devShell.env;
        };
      })));
  };
}
```

**Comment by yusdacra** [comment]
It would be possible to expose more information, but it needs to be done at a module level, possibly in dream2nix. We could probably do it NCI side but I'm not sure if that's the best way to go. I'm still not sure about it and I don't have time to come up with something there for now though.

If you want, you can PR this module into NCI probably into a `contrib` folder and expose it in the `flake.nix` (under `flakeModules` would be alright i think?).

**Comment by oddlama** [comment]
I think this already covers 95% of all projects, so if it isn't trivial to do then that's fine. I'll definitely PR this once I'm sure that it works properly.

I did just test a project with some dependencies and it seems like `PKG_CONFIG_PATH` is not exposed in the new `devShell.env` attribute. On second thought it actually looks like the whole `devShell.env` attribute is completely empty for some reason.. But the classical exposed devshell works fine. Am I missing something?

This is my crate definition, I'm basically just compiling a dummy `cargo init; cargo add bevy` project.

```nix
        nci.crates.${projectName} = rec {
          numtideDevshell = "default";
          runtimeLibs = with pkgs; [
          ];
          depsDrvConfig = {
            mkDerivation = {
              nativeBuildInputs = [pkgs.pkg-config];
              buildInputs = with pkgs; [
                alsa-lib
                libxkbcommon
                udev
                vulkan-loader
                wayland.dev
                xorg.libX11
                xorg.libXcursor
                xorg.libXi
                xorg.libXrandr
              ];
            };
          };
          drvConfig = {
            mkDerivation = {
              nativeBuildInputs = [pkgs.pkg-config];
              buildInputs = depsDrvConfig.mkDerivation.buildInputs;
            };
          };
        };
```

**Comment by yusdacra** [comment]
I'll have to look into this later (i don't have access to a pc right now) but I'm suspecting it's probably due to the way those are exposed. I kind of did it quick so I wasn't sure if it was gonna work correctly anyway, it's probably not pulling from the correct places (combined shells (for projects) pull the nci config and add env vars from there, which afterwards should be merged with the env vars with the resulting shell but I guess something is going wrong there.

**Comment by oddlama** [comment]
Thanks for the info, take your time.

**Comment by yusdacra** [comment]
investigating this more, i think why PKG_CONFIG_PATH doesn't appear in the numtide shell is because it doesn't have the necessary hooks, since that gets set in a hook from pkg-config. so you'd need to use the numtide rust / c modules to set this (iirc in the past nci also did this, it just used to throw everything that was a lib into one of those modules to set the correct env vars).

**Comment by oddlama** [comment]
Good call, that was the missing piece. It isn't even necessary to include the `language.c` or `language.rust` modules from the numtide devshell, they both do just some very basic environment setup. I've created #160 with a working implementation now which just adds all dev outputs from the libraries to the `LD_LIBRARY_PATH` and sets the `PKG_CONFIG_PATH` to the one the devshell already provides.

With these changes the example bevy project from above works perfectly :)
