### ISSUE TITLE
Shells to include their crate's `.drvConfig.env`

### ISSUE THREAD

**Issue by mightyiam** [yusdacra/nix-cargo-integration#162]
If I use `.drvConfig.env` to set some variables for the crate to be picked up at compile time, I would like to have these variables defined in my dev shell, so that `cargo build` would succeed. I think this should be the default...

**Comment by yusdacra** [comment]
this should already be the case? unless there is some bug i don't know about

**Comment by mightyiam** [comment]
Now I'm trying with the `perSystem.nci.projects.<name>.numtideDevshell` option, and loving it. This way:

```nix
  perSystem.nci = {
    projects.default = {
      path = ./.;
      numtideDevshell = "default";
    };   
    crates.foo.drvConfig.env.FOO = "1";
  };
```

And in the default devshell there's no `FOO`...

**Comment by yusdacra** [comment]
This seems to work completely fine for me, I added that line to the example and if you enter that shell you should see `FOO`.

**Comment by mightyiam** [comment]
Here's my [actual attempt](https://github.com/mobusoperandi/website/pull/274). Theoretically, that line shouldn't be necessary? But if you enter `nix develop` on that branch you won't get the variables defined in `crates/builder/default.nix`.

**Comment by yusdacra** [comment]
i looked at it more and it looks like packages were getting filtered out incorrectly, i fixed that and it should work fine now on the latest commit

**Comment by mightyiam** [comment]
Brilliant. Thank you.
