### ISSUE TITLE
`nci.projects.default.drvConfig.env` settings don't merge

### ISSUE THREAD

**Issue by jfly** [yusdacra/nix-cargo-integration#182]
We're trying to set `nci.projects.default.drvConfig.env` in 2 places in our flake, and one value seems to be clobbering the other. Here are the 2 lines of code:

- https://github.com/molybdenumsoftware/pr-tracker/blob/7ea7db7c2471d573c884b3d4a748100775917657/modules/program-docs.nix/#L15
- https://github.com/molybdenumsoftware/pr-tracker/blob/7ea7db7c2471d573c884b3d4a748100775917657/modules/nci.nix/#L12

If we comment out the setting in `modules/nci.nix`, we see the setting in `program-docs.nix` get evaluated (and thereby blow the assertion in `program-docs.nix`):

```
$ nix eval github:molybdenumsoftware/pr-tracker/0ed99949b3f0627711c43f00da5bbe99d6cafd9b#fetcher -L
«error: inside program-docs.nix. we hit this assertion because we commented out the corresponding setting in modules/nci.nix»
```

And if we do not comment out the setting in `modules/nci.nix`, we don't hit the assertion in `program-docs.nix`:

```
$ nix eval github:molybdenumsoftware/pr-tracker/bb15515#fetcher -L
«derivation /nix/store/xkvq5dkw0sqgd6lp40kdk3xds1s1sla0-pr-tracker-fetcher-4.1.1.drv»
```

(sorry for the messy branch, it's very WIP right now)

**Comment by yusdacra** [comment]
should work fine now
