### ISSUE TITLE
Release a stable 1.0 API

### ISSUE THREAD

**Issue by yusdacra** [yusdacra/nix-cargo-integration#21]
A stable API should be provided sooner or later. While much of the public API hasn't seen a change anyways, after adding some more useful features (#20) a 1.0 release should be made.

**Comment by bew** [comment]
Before the official release of flakes in Nix?

**Comment by yusdacra** [comment]
> Before the official release of flakes in Nix?

Probably. Flakes changing should not affect the API, as currently the only use of flakes for us is to provide an easier and simpler way to provide the library to users. So I don't intend to wait until flakes are stabilized.
