### ISSUE TITLE
How to use `installShellFiles` ?

### ISSUE THREAD

**Issue by pinage404** [yusdacra/nix-cargo-integration#53]
Hello,

How to put shell completions files in derivation using `installShellFiles` ?

Usually it is something like that
```nix
{
  # ...
  nativeBuildInputs = [ pkgs.installShellFiles ];
  postInstall = ''
    installShellCompletion $releaseDir/build/lsd-*/out/{_lsd,lsd.{bash,fish}}
  '';
  # ...
}
```

**Comment by yusdacra** [comment]
If you want to put them inside your package, you need to use the `crateOverrides` system. So basically:

```nix
{
	# in flake.nix, inside `makeOutputs`
	overrides = {
		crateOverrides = common: _: {
			your_package_name = prev: {
				nativeBuildInputs = (prev.nativeBuildInputs or [ ]) ++ [ pkgs.installShellFiles ];
  				postInstall = "
					${prev.postInstall or ""}
    				installShellCompletion $releaseDir/build/lsd-*/out/{_lsd,lsd.{bash,fish}}
  				";
			};
		};
	};
	# ...
}
```

This is kind of boilerplate-y right now as if you want to keep changes by other overrides, you need to use `prev.` a lot. When #49 lands, I will add an option to use dream2nix override system directly instead, which is a lot more user friendly.

**Comment by pinage404** [comment]
It [works](https://gitlab.com/pinage404/git-gamble/-/commit/9c13a7b7e9b4b6d1cbecd3e470a2a844d94e5ad8)

Thanks =)
