### ISSUE TITLE
How do I provide `src` instead of `root`?

### ISSUE THREAD

**Issue by a-kenji** [yusdacra/nix-cargo-integration#61]
Hey! Thanks for this builder!
How do I give it a `src` instead of the `root` of a crate?

**Comment by yusdacra** [comment]
Can you be more specific? The `root` should point to the root of a crate *or* a workspace if the crate is in one.

**Comment by a-kenji** [comment]
Sure! I don't know if this is necessary here. Usually you need to provide the `src` attribute in builds, so you can for example ignore files and directories that are not inside the `gitignore`, but don't need to be included in the process.

**Comment by yusdacra** [comment]
> Sure! I don't know if this is necessary here. Usually you need to provide the `src` attribute in builds, so you can for example ignore files and directories that are not inside the `gitignore`, but don't need to be included in the process.

You should essentially just provide `root` what you would provide if it was `src`, think of it like that.

**Comment by a-kenji** [comment]
Oh! Alright, thank you!

**Comment by a-kenji** [comment]
Ah, I can't provide to `root` what I would provide to `src` usually, I get this error:
```
the string '/nix/store/6h0dzcsk1dc6znwk2k38bzwxxmp9yxrc-source/rust-toolchain.toml' is not allowed to refer to a store path (such as '/nix/store/6h0dzcsk1dc6znwk2k38bzwxxmp9yxrc-source')
```

But that is not a big deal. I will just provide the path for now.

**Comment by taaylormoon** [comment]
Where does this error manifest?
