### ISSUE TITLE
Override stdenv version

### ISSUE THREAD

**Issue by jdahm** [yusdacra/nix-cargo-integration#65]
Is it possible to override the stdenv version? I see [this](https://github.com/yusdacra/nix-cargo-integration/blob/d2c0b605e2fe7ba4926a28555c8b297ba05f8571/src/createNixpkgsDrv.nix#L54) but it looks like the version isn't possible to set. I have a use-case in helix where some C compiler flags are used that may only be supported in clang > 11 versions.

**Comment by yusdacra** [comment]
If you mean the compiler version, that is possible through setting the `cCompiler` argument under `[package.metadata.nix]` in `Cargo.toml`, to something like `clang` etc. (a compiler package attribute path). You can't set this from nix code (yet), and it's not documented (although it should have been).

`nix-cargo-integration` uses `stdenvNoCc` and provides compiler through what the user specifies. I'm aware this is not ideal, so I will introduce a way to set stdenv.

**Comment by jdahm** [comment]
I'd like to set the cCompiler via `[package.metadata.nix]` as you say or as an argument to `overrides` in `nixCargoIntegration.lib.makeOutputs` such as:

```
overrides = {
  packageMetadata = _: { cCompiler = "clang"; };
  ...
};
```

The problem is that in both cases I don't know how to access the system type. Some system checks are exposed through `nixCargoIntegration` later in `common.pkgs.stdenv` (e.g. `isDarwin`, etc.) but I don't seem to have access to that when setting `packageMetadata`. Can you think of a way to get at that there or in the `Cargo.toml` file for `[package.metadata.nix]`? Thanks for the help!

**Comment by yusdacra** [comment]
I opened #70 for this. It adds a new `overrides.cCompiler` that `nix-cargo-integration` supports, which can be used to set the C compiler that will be used. You can check the manual in that PR to see how to use it.

**Comment by yusdacra** [comment]
@jdahm just mentioning you to make sure you see this :)

**Comment by jdahm** [comment]
Thanks! This seems to be working on https://github.com/helix-editor/helix/pull/1789. I'm just sorting out another issue there.

**Comment by NickHu** [comment]
Is this still possible in the new version?
