### ISSUE TITLE
dream-lock.json doesn't exist

### ISSUE THREAD

**Issue by khrj** [yusdacra/nix-cargo-integration#66]
When I build my app with `nix build`, I get

```
trace:

The dream-lock.json for input 'app' doesn't exist or is outdated.
...Falling back to on-the-fly evaluation (possibly slow).
To speed up future evalutations run once:
  nix run .#resolve
```
(this doesn't terminate the build, and it works fine)

Running `nix run .#resolve` shows that an output called resolve doesn't exist

```
error: cannot find flake attribute 'git+file:///<the-app-directory>/app#resolve'
```

**Comment by yusdacra** [comment]
This is not really an issue, it doesn't affect how `nix-cargo-integration` behaves. The warning doesn't matter for our case. Adding a way to disable it in `dream2nix` per translator would be useful for this.

**Comment by yusdacra** [comment]
This shouldn't happen anymore now that `nix-cargo-integration` uses latest dream2nix which has these warnings disabled.
