### ISSUE TITLE
Invalid crate2nix revision

### ISSUE THREAD

**Issue by malte-v** [yusdacra/nix-cargo-integration#7]
https://github.com/yusdacra/nix-cargo-integration/blob/34b5ac16983ef0575721b00a5c7e45d566de37e5/flake.nix#L24

This commit is not part of the repository, causing Nix builds to fail: https://github.com/yusdacra/crate2nix/commit/f7f96a6a84e66d54213a9f09036810620bb1b049

**Comment by yusdacra** [comment]
Sorry, it should be fixed now.

**Comment by malte-v** [comment]
Thanks!
