### ISSUE TITLE
libclang.lib not included in nix develop shell

### ISSUE THREAD

**Issue by olafklingt** [yusdacra/nix-cargo-integration#78]
If you use Cargo.toml to define nix specific configurations, `cargo build` fails if both `libclang` and `libclang.lib` are defined in common `buildInputs`. As it can be seen here: https://github.com/olafklingt/pw-viz-flaked/blob/nix-cargo-integration-cargo-toml-broken/Cargo.toml#L44-L45

**Comment by yusdacra** [comment]
I *think* this should no longer be an issue, but please re-open this if you can verify that it is. I tested myself with latest nci and the build seems to fail regardless so it seems to be unrelated to this...
