### ISSUE TITLE
Include `shell.nix`, a-la flake-utils `simpleFlake`

### ISSUE THREAD

**Issue by bobbbay** [yusdacra/nix-cargo-integration#85]
`flake-utils` has a `simpleFlake` output that allows the following flake format:

```nix
{
  description = "Flake utils demo";

  inputs.flake-utils.url = "github:numtide/flake-utils";

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.simpleFlake {
      inherit self nixpkgs;
      name = "simple-flake";

      # NOTABLY:
      shell = ./shell.nix;
    };
}
```

I have a `shell.nix` that includes things that `nix-cargo-integration`'s overrides system does not allow, e.g. `mkShell.override { ... }`:

```nix
{pkgs ? import <nixpkgs> {}}:
with pkgs;
  (mkShell.override {stdenv = llvmPackages_11.stdenv;}) {
    buildInputs = [
      ...
    ];
  }

```

I would like to be able to use this shell.nix file - including, and especially, the call to `mkShell.override` - from `nix-cargo-integration`. Is this possible?

**Comment by yusdacra** [comment]
This isn't possible because NCI uses `devshell`, which doesn't exactly use a `stdenv`. NCI allows you to set the C compiler used through `overrides.cCompiler`, but otherwise it doesn't provide anything else. You should also just be able to add `${stdenv}/setup` to setup the stdenv however. As for having a separate `shell.nix` file, you can do something like:

```nix
# shell.nix
common: prev: {
	packages = prev.packages ++ [ ];
}
```
and
```nix
# flake.nix
{
	outputs = {nci, ...}:
		nci.lib.makeOutputs {
			# ...
			overrides.shell = import ./shell.nix;
			# ...
		};
}
```
should work.

**Comment by bobbbay** [comment]
I'm willing to go with the first option (setting `cCompiler` and using `{stdenv}/setup`), but I honestly don't understand where to include the setup file in my flake. Does it go in a derivation in `overrides.packages`?

**Comment by yusdacra** [comment]
If you want to use it in your shell, it should be fine to include it in a shell hook like so:
```nix
# shell.nix
common: prev: {
	startup = prev.startup // {
		setupStdenv.text = "${stdenv}/setup";
	};
}
```

**Comment by bobbbay** [comment]
Strangely, I can't find the `startup` attribute in the documentation, what is it under? It doesn't work under `overrides` or `overrides.shell`, unfortunately.

**Comment by yusdacra** [comment]
sorry, it should've been:
```nix
# shell.nix
common: prev: {
	devshell = prev.devshell // {
		startup = prev.devshell.startup // {
			setupStdenv.text = "${stdenv}/setup";
		};
	};
}
```

**Comment by yusdacra** [comment]
> Strangely, I can't find the startup attribute in the documentation, what is it under? It doesn't work under overrides or overrides.shell, unfortunately.

You can find those here https://numtide.github.io/devshell/modules_schema.html . Currently NCI doesn't utilize the module system but I'm working towards it so that the interface will use modules completely, which should make errors better, and the code should be self-documenting.

**Comment by bobbbay** [comment]
Alright, thank you for the help!
