### ISSUE TITLE
Mutiple runtime libs result in none of them being in LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by uzytkownik** [yusdacra/nix-cargo-integration#90]
```
{
  inputs = {
    nixCargoIntegration.url = "github:yusdacra/nix-cargo-integration";
  };

  outputs = inputs: inputs.nixCargoIntegration.lib.makeOutputs {
    root = ./.;
    config = common: {
      shell = {
        packages = [common.pkgs.pkg-config common.pkgs.alsa-lib];
      };
      runtimeLibs = [
        common.pkgs.xorg.libX11
      ];
    };
    pkgConfig = common: {
      "creepers" = {
        depsOverrides = {
          sys-deps = {
            buildInputs = [common.pkgs.pkg-config common.pkgs.alsa-lib common.pkgs.udev];
          };
        };
      };
    };
  };
}
```

Shows that $LD_LIBRARY_PATH is `/nix/store/8bf8li7ajgb15ivpy2gsbaf7111jpb21-libX11-1.7.2/lib:/nix/store/1166267pz76awyfswidh3rz995xq8kyh-devshell-dir/lib:/nix/store/am86zfqj5pmfbf9mm822hzfd4d6372aw-sane-config/lib/sane:/nix/store/7li4k00ri8siawwi8vdibbdmsaiwd18i-pipewire-0.3.56-jack/lib`

However if I change it to:

```
      runtimeLibs = [
        common.pkgs.xorg.libX11
        common.pkgs.xorg.libXcursor
      ];
```

I got an error `/nix/store/n95s7s6ilkjc7xwqml93acxzj6k0hsfn-coreutils-9.1/bin/realpath: '/nix/store/8bf8li7ajgb15ivpy2gsbaf7111jpb21-libX11-1.7.2/lib:/nix/store/9w8qaifxnwg8mdxmcbwd79gjw3p27acs-libXcursor-1.2.0/lib': No such file or directory` and X11 and Xcursor are not in path.

**Comment by yusdacra** [comment]
Thanks for the report, does the latest master fix this issue for you?

**Comment by yusdacra** [comment]
closing since I believe this is fixed now
