### ISSUE TITLE
Request: option for building/running other profiles 

### ISSUE THREAD

**Issue by nothingnesses** [yusdacra/nix-cargo-integration#93]
Prior discussion at #92.

**Comment by yusdacra** [comment]
I've made a PR #97 to support this feature, it would be awesome if you could test it. The new field `profiles` is documented and is also shown in the example flake.

**Comment by nothingnesses** [comment]
Nice, building with a custom profile seems to work! Thanks for the quick update!

Btw, I noticed when running `nix flake show` that there seems to be derivations for platforms other than the one I'm using (I'm on x86_64-linux and yet there are derivations for darwin and aarch64 platforms). Does this mean nci can be use for cross-compilation? If so, how? And how would I cross-compile for other targets that aren't listed (e.g. for mingw32)?
